### PR TITLE
save file before running program

### PR DESCRIPTION
**Pull request by toklinke**
- the file is automatically saved when 'Run' button is clicked
- if the file has not been saved yet, the save dialog is shown

I think the handling of the modal dialogs is not quite clean. I think it could be refactored so that the event handlers for the buttons are decoupled from the HTML. Then the callback handling could be simplified.

### CODE REVIEW

**Comment by JonasTrampe** [comment]
webserver/static/js/webserver.js+41: Shouldn't this be changed to execute(), too?

**Comment by SaschaMzH** [comment]
[Save before run automatically](https://trello.com/c/bztsJKqD/20-save-before-run-automatically)

**Comment by toklinke** [comment]
@JonasTrampe 
> 
> 
> webserver/static/js/webserver.js+41: Shouldn't this be changed to execute(), too?

In fact, I have just noticed that currently none of the shortcut keys work.
I have fixed Ctrl+R shortcut. Shall I open an issue for the other shortcut keys?

**Comment by SaschaMzH** [comment]
Yes please crate an issue for the shortcuts

**Pull request merged**
